
base.uri = https://jsonplaceholder.typicode.com

# to disable SSL set this to true
ssl.relaxed = true

# Authentications - NONE, BASIC, BEARER, OAUTH2, API_KEY
auth.type=NONE

# set logging true for local debugging
enable.logging=false